# Generated by Django 2.1.5 on 2020-07-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=10)),
                ('number', models.IntegerField(max_length=655)),
                ('message', models.TextField()),
                ('name', models.CharField(max_length=300)),
            ],
        ),
    ]
