# Generated by Django 2.1.5 on 2020-07-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animations', '0002_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='number',
            field=models.IntegerField(max_length=55),
        ),
    ]
