# Generated by Django 2.1.5 on 2020-07-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animations', '0003_auto_20200717_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='number',
            field=models.IntegerField(),
        ),
    ]
