# Generated by Django 2.1.5 on 2020-07-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animations', '0004_auto_20200717_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(max_length=299),
        ),
    ]
