# Generated by Django 2.1.5 on 2020-07-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animations', '0006_auto_20200718_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=299)),
            ],
        ),
    ]
